local navic = require("nvim-navic")
local symbol_map = require("kide.lsp.lsp_ui").symbol_map
navic.setup({
  icons = {
    File = symbol_map.File.icon .. " ",
    Module = symbol_map.Module.icon .. " ",
    Namespace = symbol_map.Namespace.icon .. " ",
    Package = symbol_map.Package.icon .. " ",
    Class = symbol_map.Class.icon .. " ",
    Method = symbol_map.Method.icon .. " ",
    Property = symbol_map.Property.icon .. " ",
    Field = symbol_map.Field.icon .. " ",
    Constructor = symbol_map.Constructor.icon .. " ",
    Enum = symbol_map.Enum.icon .. "",
    Interface = symbol_map.Interface.icon .. "",
    Function = symbol_map.Function.icon .. " ",
    Variable = symbol_map.Variable.icon .. " ",
    Constant = symbol_map.Constant.icon .. " ",
    String = symbol_map.String.icon .. " ",
    Number = symbol_map.Number.icon .. " ",
    Boolean = symbol_map.Boolean.icon .. " ",
    Array = symbol_map.Array.icon .. " ",
    Object = symbol_map.Object.icon .. " ",
    Key = symbol_map.Key.icon .. " ",
    Null = symbol_map.Null.icon .. " ",
    EnumMember = symbol_map.EnumMember.icon .. " ",
    Struct = symbol_map.Struct.icon .. " ",
    Event = symbol_map.Event.icon .. " ",
    Operator = symbol_map.Operator.icon .. " ",
    TypeParameter = symbol_map.TypeParameter.icon .. " ",
  },
  -- highlight = false,
  separator = "  ",
  -- depth_limit = 0,
  -- depth_limit_indicator = "..",
})
